import { PrismaClient } from "@prisma/client";
import bcrypt from "bcryptjs";

const prisma = new PrismaClient();

async function main() {
  console.log("🌱 Seeding Treyfa database...");

  // ─── Users ───────────────────────────────────────────────────────────────
  const adminPassword = await bcrypt.hash("admin123", 12);
  const userPassword = await bcrypt.hash("user123", 12);

  await prisma.user.upsert({
    where: { email: "admin@treyfa.in" },
    update: {},
    create: {
      email: "admin@treyfa.in",
      name: "Treyfa Admin",
      password: adminPassword,
      role: "ADMIN",
    },
  });

  await prisma.user.upsert({
    where: { email: "user@treyfa.in" },
    update: {},
    create: {
      email: "user@treyfa.in",
      name: "Test User",
      password: userPassword,
      role: "USER",
    },
  });

  console.log("✅ Users created");

  // ─── Categories ──────────────────────────────────────────────────────────
  const faceCareCat = await prisma.category.upsert({
    where: { slug: "face-care" },
    update: {},
    create: {
      name: "Face Care",
      slug: "face-care",
      description: "Natural & herbal face washes and skincare formulated with turmeric, neem, and choco coffee for clear, glowing skin.",
      image: "https://treyfa.in/wp-content/uploads/2024/11/BOX-FRIST-PAGE-SAMPLE-9-406x406.png",
      isActive: true,
    },
  });

  const hairCareCat = await prisma.category.upsert({
    where: { slug: "hair-care" },
    update: {},
    create: {
      name: "Hair Care",
      slug: "hair-care",
      description: "Traditional South Indian herbal hair oils, shampoos and conditioners for hair growth, dandruff control and deep nourishment.",
      image: "https://treyfa.in/wp-content/uploads/2024/11/BOX-FRIST-PAGE-SAMPLEN-Recovered-8-406x406.png",
      isActive: true,
    },
  });

  const bathBodyCat = await prisma.category.upsert({
    where: { slug: "bath-body-care" },
    update: {},
    create: {
      name: "Bath & Body Care",
      slug: "bath-body-care",
      description: "Pure herbal bath and body care products made with natural ingredients for skin restoration and total body wellness.",
      image: "https://treyfa.in/wp-content/uploads/2025/04/100-ml-1-406x406.jpg",
      isActive: true,
    },
  });

  console.log("✅ Categories created");

  // ─── Products ────────────────────────────────────────────────────────────

  // ── Face Care Products (8) ────────────────────────────────────────────
  const faceProducts = [
    {
      name: "Choco Coffee Face Wash – Foaming, Fresh & Hydrating 100ML",
      slug: "choco-coffee-face-wash-100ml",
      description: "A premium foaming face wash combining the power of chocolate and coffee to deeply cleanse, hydrate, and energize your skin. The caffeine in coffee tightens pores and reduces puffiness, while cocoa antioxidants combat free radicals. Leaves skin feeling fresh, supple, and naturally radiant. Suitable for all skin types. Free from harmful chemicals — India's cancer-free cosmetics.",
      price: 170,
      comparePrice: 299,
      stock: 150,
      sku: "FC-CCW-100",
      images: [
        "https://treyfa.in/wp-content/uploads/2025/03/100-ml-1-406x406.png",
        "https://treyfa.in/wp-content/uploads/2025/03/07-2-406x406.jpg",
      ],
      tags: ["face-wash", "choco-coffee", "foaming", "hydrating", "100ml"],
      isFeatured: true,
      rating: 5.0,
      reviewCount: 17,
      categoryId: faceCareCat.id,
    },
    {
      name: "Herbal Neem Foaming Face Wash for Pimples & Oil Control 150ML",
      slug: "herbal-neem-foaming-face-wash-150ml",
      description: "Specially formulated with the antibacterial power of neem to combat acne, pimples and excess sebum. This foaming face wash penetrates deep into pores, eliminating bacteria responsible for breakouts while balancing the skin's natural oil production. Enhanced with herbal extracts for a thorough yet gentle cleanse. Ideal for oily, acne-prone skin. Chemical-free formulation.",
      price: 180,
      comparePrice: 359,
      stock: 120,
      sku: "FC-NNW-150",
      images: [
        "https://treyfa.in/wp-content/uploads/2024/11/BOX-FRIST-PAGE-SAMPLE-2-406x406.png",
        "https://treyfa.in/wp-content/uploads/2024/11/01-3.jpg",
      ],
      tags: ["face-wash", "neem", "acne", "oil-control", "150ml"],
      isFeatured: false,
      rating: 4.94,
      reviewCount: 16,
      categoryId: faceCareCat.id,
    },
    {
      name: "Neem Face Wash – Foaming, Acne Control & Oil-Free Glow 100ML",
      slug: "neem-face-wash-100ml",
      description: "Harness the centuries-old power of neem in this compact foaming face wash. Neem's natural antibacterial and antifungal properties fight acne at the source, while its anti-inflammatory compounds soothe redness and irritation. Regular use reveals a visibly clearer, oil-free complexion with a healthy glow. Perfect for daily use on oily to combination skin.",
      price: 170,
      comparePrice: 299,
      stock: 200,
      sku: "FC-NFW-100",
      images: [
        "https://treyfa.in/wp-content/uploads/2025/03/100-ml-406x406.jpg",
        "https://treyfa.in/wp-content/uploads/2025/03/01-406x406.jpg",
      ],
      tags: ["face-wash", "neem", "acne-control", "oil-free", "100ml"],
      isFeatured: true,
      rating: 5.0,
      reviewCount: 14,
      categoryId: faceCareCat.id,
    },
    {
      name: "Pure Virgin Vetiver Coconut Oil – 2-in-1 Hair & Skin Nourishment 200ML",
      slug: "pure-vetiver-coconut-oil-hair-skin-200ml",
      description: "A luxurious dual-purpose oil blending pure virgin coconut oil with cooling vetiver (khus) root. Vetiver's deep-earthy aroma calms the mind while its skin-regenerating properties reduce pigmentation, heal scars, and restore natural radiance. As a hair oil, it strengthens roots, prevents breakage, and imparts deep conditioning from scalp to tip. 100% natural, free of mineral oils and silicones.",
      price: 220,
      comparePrice: 399,
      stock: 80,
      sku: "FC-VCO-200",
      images: [
        "https://treyfa.in/wp-content/uploads/2024/11/BOX-FRIST-PAGE-SAMPLEN-Recovered-8-406x406.png",
        "https://treyfa.in/wp-content/uploads/2024/11/02-30.jpg",
      ],
      tags: ["face-oil", "vetiver", "coconut-oil", "2-in-1", "200ml", "skin-care"],
      isFeatured: true,
      rating: 5.0,
      reviewCount: 11,
      categoryId: faceCareCat.id,
    },
    {
      name: "Treyfa Foaming Turmeric Face Wash – Revitalize & Glow Naturally 100ML",
      slug: "turmeric-face-wash-100ml",
      description: "Infused with the golden goodness of turmeric (haldi), this foaming cleanser targets uneven skin tone, dark spots and dullness. Curcumin — turmeric's active compound — is a potent antioxidant that fights inflammation and brightens complexion naturally. The gentle foam lifts impurities without stripping moisture. For all skin types seeking natural luminosity.",
      price: 170,
      comparePrice: 299,
      stock: 180,
      sku: "FC-TFW-100",
      images: [
        "https://treyfa.in/wp-content/uploads/2025/03/100-ml-1-406x406.jpg",
        "https://treyfa.in/wp-content/uploads/2025/03/01-1-406x406.jpg",
      ],
      tags: ["face-wash", "turmeric", "glow", "brightening", "100ml"],
      isFeatured: false,
      rating: 5.0,
      reviewCount: 10,
      categoryId: faceCareCat.id,
    },
    {
      name: "Treyfa Turmeric Foaming Face Wash for Clear & Glowing Skin 150ML",
      slug: "turmeric-foaming-face-wash-150ml",
      description: "A larger-format version of our bestselling turmeric cleanser, ideal for daily use or sharing. Enriched with pure turmeric extract, this foaming face wash works overtime to fade blemishes, even out skin tone, and deliver a radiant, lit-from-within glow. Formulated without parabens, sulfates, or artificial fragrances. Suitable for all skin types including sensitive skin.",
      price: 180,
      comparePrice: 359,
      stock: 110,
      sku: "FC-TFW-150",
      images: [
        "https://treyfa.in/wp-content/uploads/2024/11/BOX-FRIST-PAGE-SAMPLE-9-406x406.png",
        "https://treyfa.in/wp-content/uploads/2024/11/01-2-scaled-1.jpg",
      ],
      tags: ["face-wash", "turmeric", "clear-skin", "glowing", "150ml"],
      isFeatured: true,
      rating: 5.0,
      reviewCount: 1,
      categoryId: faceCareCat.id,
    },
    {
      name: "Ultimate Choco Coffee Face Wash 150ML",
      slug: "choco-coffee-face-wash-150ml",
      description: "Our most indulgent face wash experience. Comes with a complimentary silicone brush head for deep pore cleansing. The rich chocolate-coffee formula exfoliates dead skin cells, stimulates microcirculation, and deeply nourishes the skin. Coffee's natural astringency tightens pores while cocoa butter moisturizes intensely. A truly premium everyday cleansing ritual.",
      price: 180,
      comparePrice: 359,
      stock: 90,
      sku: "FC-CCW-150",
      images: [
        "https://treyfa.in/wp-content/uploads/2024/11/BOX-FRIST-PAGE-SAMPLE-34-406x406.png",
        "https://treyfa.in/wp-content/uploads/2024/11/9ZANDE9U_02-4-30-2022-4-04-04PM.webp",
      ],
      tags: ["face-wash", "choco-coffee", "exfoliating", "silicone-brush", "150ml"],
      isFeatured: true,
      rating: 5.0,
      reviewCount: 1,
      categoryId: faceCareCat.id,
    },
    {
      name: "Virgin Coconut Vetiver Hair Oil – Soothing & Deeply Nourishing 100ML",
      slug: "virgin-coconut-vetiver-hair-oil-100ml",
      description: "A therapeutic blend of cold-pressed virgin coconut oil and pure vetiver root extract. Vetiver's cooling properties soothe an irritated scalp while its deep penetrating action nourishes hair follicles from within. Regular application reduces hair fall, strengthens brittle strands, and imparts a glossy sheen. Absorbs quickly without leaving greasy residue. Safe for color-treated hair.",
      price: 175,
      comparePrice: 299,
      stock: 140,
      sku: "FC-VHO-100",
      images: [
        "https://treyfa.in/wp-content/uploads/2025/03/100ml-406x406.jpg",
        "https://treyfa.in/wp-content/uploads/2025/03/01-7-406x406.jpg",
      ],
      tags: ["hair-oil", "vetiver", "coconut-oil", "nourishing", "100ml"],
      isFeatured: false,
      rating: 5.0,
      reviewCount: 8,
      categoryId: faceCareCat.id,
    },
  ];

  // ── Hair Care Products ────────────────────────────────────────────────
  const hairProducts = [
    {
      name: "2-in-1 Neem Dandruff Shampoo + Conditioner – Herbal Flake Control 100ML",
      slug: "neem-dandruff-shampoo-100ml",
      description: "A powerful 2-in-1 herbal solution combining the antibacterial strength of neem with deep conditioning agents. Neem's antifungal properties target Malassezia — the fungus responsible for dandruff — while eliminating flakes, reducing itching, and balancing scalp pH. The conditioner component smooths the cuticle for manageable, frizz-free hair. Ideal for chronic dandruff sufferers.",
      price: 170,
      comparePrice: 299,
      stock: 200,
      sku: "HC-NDS-100",
      images: [
        "https://treyfa.in/wp-content/uploads/2025/03/100-ML-3-406x406.jpg",
        "https://treyfa.in/wp-content/uploads/2025/03/01-4-406x406.jpg",
      ],
      tags: ["shampoo", "conditioner", "neem", "dandruff", "2-in-1", "100ml"],
      isFeatured: true,
      rating: 4.58,
      reviewCount: 45,
      categoryId: hairCareCat.id,
    },
    {
      name: "Basil Heaven Basil Healing Oil – Herbal Formula for Skin Restoration 100ML",
      slug: "basil-healing-oil-heaven-100ml",
      description: "Sacred basil (Tulsi) has been revered in Ayurveda for thousands of years. This concentrated healing oil captures Tulsi's adaptogenic and antimicrobial properties to restore damaged hair and nourish the scalp. Rich in essential oils, it stimulates blood circulation to hair follicles, promoting growth while its antibacterial action keeps scalp infections at bay. Also effective as a body care oil.",
      price: 175,
      comparePrice: 299,
      stock: 120,
      sku: "HC-BHO-100",
      images: [
        "https://treyfa.in/wp-content/uploads/2025/04/100-ml-1-406x406.jpg",
        "https://treyfa.in/wp-content/uploads/2025/04/01-406x406.jpg",
      ],
      tags: ["hair-oil", "basil", "tulsi", "healing", "100ml"],
      isFeatured: false,
      rating: 4.73,
      reviewCount: 37,
      categoryId: hairCareCat.id,
    },
    {
      name: "Coconut & Neem Natural Anti-Dandruff Oil 200ML",
      slug: "coconut-neem-anti-dandruff-oil-200ml",
      description: "A synergistic blend of coconut oil and neem that addresses dandruff at its root. Virgin coconut oil provides deep scalp moisturization preventing the dryness that triggers flaking, while neem's potent antifungal compounds eliminate the underlying fungal cause of dandruff. This oil also soothes scalp psoriasis and seborrheic dermatitis. Apply weekly for best results.",
      price: 200,
      comparePrice: 399,
      stock: 100,
      sku: "HC-CNA-200",
      images: [
        "https://treyfa.in/wp-content/uploads/2024/11/BOX-FRIST-PAGE-SAMPLEN-Recovered-4-406x406.png",
        "https://treyfa.in/wp-content/uploads/2024/11/01-24.jpg",
      ],
      tags: ["hair-oil", "coconut", "neem", "anti-dandruff", "200ml"],
      isFeatured: false,
      rating: 4.93,
      reviewCount: 15,
      categoryId: hairCareCat.id,
    },
    {
      name: "Coconut Chamomile Hibiscus Hair Oil 200ML",
      slug: "coconut-chamomile-hibiscus-hair-oil-200ml",
      description: "A luxurious triple-botanical blend inspired by South Indian hair traditions. Hibiscus — known as the 'flower of hair care' — strengthens hair roots and adds natural sheen. Chamomile soothes the scalp and imparts a golden brightness to hair. Virgin coconut penetrates the hair shaft for deep protein retention. Together, they create a powerfully restorative and aromatic hair oil.",
      price: 200,
      comparePrice: 399,
      stock: 90,
      sku: "HC-CCH-200",
      images: [
        "https://treyfa.in/wp-content/uploads/2024/11/BOX-FRIST-PAGE-SAMPLEN-406x406.png",
        "https://treyfa.in/wp-content/uploads/2024/11/01-15.jpg",
      ],
      tags: ["hair-oil", "coconut", "chamomile", "hibiscus", "200ml"],
      isFeatured: false,
      rating: 4.88,
      reviewCount: 16,
      categoryId: hairCareCat.id,
    },
    {
      name: "Coconut Oil for Hair Growth 100ML",
      slug: "coconut-oil-for-hair-growth-100ml",
      description: "A specially formulated coconut oil blend designed to accelerate hair growth and combat thinning. Enriched with growth-activating herbal extracts, this oil penetrates the hair follicle to deliver nutrients directly to the root zone. Medium-chain fatty acids in coconut oil reduce protein loss from hair, while lauric acid has high affinity for hair proteins. Use 2–3 times per week for visible results in 4–6 weeks.",
      price: 175,
      comparePrice: 299,
      stock: 160,
      sku: "HC-CGO-100",
      images: [
        "https://treyfa.in/wp-content/uploads/2025/03/100-ML-5-406x406.jpg",
        "https://treyfa.in/wp-content/uploads/2025/03/01-6-406x406.jpg",
      ],
      tags: ["hair-oil", "coconut", "hair-growth", "100ml"],
      isFeatured: false,
      rating: 4.92,
      reviewCount: 12,
      categoryId: hairCareCat.id,
    },
    {
      name: "Cold Pressed Virgin Coconut Oil for Hair Growth 30ML",
      slug: "cold-pressed-virgin-coconut-oil-30ml",
      description: "Travel-sized pure cold-pressed virgin coconut oil, extracted without heat to preserve all nutrients, enzymes, and antioxidants. Cold-pressing retains the natural fragrance and maximum lauric acid content (≥47%). Perfect for on-the-go hair nourishment, pre-wash treatment, or testing before committing to a larger bottle. No additives, no preservatives — just 100% pure coconut goodness.",
      price: 65,
      comparePrice: 72,
      stock: 300,
      sku: "HC-VCO-30",
      images: [
        "https://treyfa.in/wp-content/uploads/2025/04/30ml-11-406x406.jpg",
        "https://treyfa.in/wp-content/uploads/2025/04/01-13-406x406.jpg",
      ],
      tags: ["hair-oil", "coconut", "cold-pressed", "30ml", "travel-size"],
      isFeatured: false,
      rating: 5.0,
      reviewCount: 11,
      categoryId: hairCareCat.id,
    },
    {
      name: "Herbal Hibiscus Shampoo for Hair Growth & Hair Fall Control 200ML",
      slug: "hibiscus-shampoo-hair-growth-200ml",
      description: "A richly lathering herbal shampoo powered by hibiscus — nature's best-kept secret for hair growth. Hibiscus is packed with vitamin C, amino acids, and alpha hydroxy acids that stimulate dormant hair follicles, reduce premature greying, and prevent hair fall from the root. This dual-action formula promotes new growth while fortifying existing strands. Sulfate-free, paraben-free.",
      price: 200,
      comparePrice: 399,
      stock: 130,
      sku: "HC-HHS-200",
      images: [
        "https://treyfa.in/wp-content/uploads/2025/05/200ml-406x406.jpg",
        "https://treyfa.in/wp-content/uploads/2025/05/01-1-406x406.jpg",
      ],
      tags: ["shampoo", "hibiscus", "hair-growth", "hair-fall", "200ml"],
      isFeatured: true,
      rating: 4.65,
      reviewCount: 26,
      categoryId: hairCareCat.id,
    },
    {
      name: "Hibiscus Conditioner for Deep Hair Repair & Smooth Hair 200ML",
      slug: "hibiscus-conditioner-deep-hair-repair-200ml",
      description: "An intensively reparative conditioner formulated with hibiscus and deep conditioning agents to restore hair compromised by heat styling, chemical treatments, or environmental damage. Hibiscus's natural mucilage forms a protective coating over each strand, locking in moisture and drastically reducing breakage. Hair becomes noticeably smoother, shinier, and more manageable from the first wash.",
      price: 200,
      comparePrice: 399,
      stock: 110,
      sku: "HC-HCD-200",
      images: [
        "https://treyfa.in/wp-content/uploads/2025/05/200-ML-406x406.jpg",
        "https://treyfa.in/wp-content/uploads/2025/04/04-14-406x406.jpg",
      ],
      tags: ["conditioner", "hibiscus", "repair", "smooth", "200ml"],
      isFeatured: false,
      rating: 4.87,
      reviewCount: 15,
      categoryId: hairCareCat.id,
    },
    {
      name: "Hibiscus Conditioner for Dry & Damaged Hair 30ML",
      slug: "hibiscus-conditioner-dry-damaged-30ml",
      description: "A concentrated travel-sized conditioner specifically designed for dry, brittle, and chemically damaged hair. The hibiscus extract binds moisture to hair fibers while natural emollients fill the gaps in the damaged cuticle. Use after every shampoo to detangle, soften, and restore elasticity. An ideal companion for frequent travelers who refuse to compromise on hair care.",
      price: 60,
      comparePrice: 72,
      stock: 250,
      sku: "HC-HCD-30",
      images: [
        "https://treyfa.in/wp-content/uploads/2025/04/30ML-12-406x406.jpg",
        "https://treyfa.in/wp-content/uploads/2025/04/01-14-406x406.jpg",
      ],
      tags: ["conditioner", "hibiscus", "dry-hair", "damaged-hair", "30ml"],
      isFeatured: false,
      rating: 4.80,
      reviewCount: 10,
      categoryId: hairCareCat.id,
    },
    {
      name: "Intense Coconut Henna Black Hair Oil 30ML",
      slug: "coconut-henna-black-hair-oil-30ml",
      description: "A travel-sized version of our popular henna-infused coconut oil for naturally darkening and strengthening hair. Henna's lawsone molecule binds to hair keratin, gradually imparting a rich dark tone while reinforcing the hair structure. Coconut oil carries these active compounds deep into the hair shaft. Regular use results in noticeably darker, stronger, and shinier hair without harsh chemicals.",
      price: 65,
      comparePrice: 72,
      stock: 200,
      sku: "HC-CHB-30",
      images: [
        "https://treyfa.in/wp-content/uploads/2025/04/30ml-3-406x406.jpg",
        "https://treyfa.in/wp-content/uploads/2025/04/01-6-406x406.jpg",
      ],
      tags: ["hair-oil", "henna", "coconut", "black-hair", "30ml"],
      isFeatured: false,
      rating: 5.0,
      reviewCount: 15,
      categoryId: hairCareCat.id,
    },
    {
      name: "Nourishing Coconut Curry Leaves Hair Oil 200ML",
      slug: "coconut-curry-leaves-hair-oil-200ml",
      description: "Curry leaves have been a cornerstone of South Indian hair care for generations. Rich in beta-carotene, proteins, and amino acids, curry leaves strengthen hair from root to tip, prevent premature greying, and deeply nourish the scalp. Combined with cold-pressed coconut oil, this blend promotes exceptional hair growth, reduces shedding, and imparts a lustrous natural shine.",
      price: 200,
      comparePrice: 399,
      stock: 95,
      sku: "HC-CCL-200",
      images: [
        "https://treyfa.in/wp-content/uploads/2024/11/BOX-FRIST-PAGE-SAMPLEN-Recovered-5-406x406.png",
        "https://treyfa.in/wp-content/uploads/2024/11/01-26.jpg",
      ],
      tags: ["hair-oil", "curry-leaves", "coconut", "strengthen", "200ml"],
      isFeatured: false,
      rating: 5.0,
      reviewCount: 15,
      categoryId: hairCareCat.id,
    },
    {
      name: "Nourishing Hibiscus Conditioner – For Hair Growth & Strength 100ML",
      slug: "hibiscus-conditioner-hair-growth-100ml",
      description: "A growth-focused conditioner that goes beyond detangling to actively strengthen and encourage hair growth. Hibiscus extract is rich in natural proteins that bond to damaged areas of hair, rebuilding strength and elasticity. Combined with nourishing botanical oils, this conditioner leaves hair noticeably thicker, bouncier, and more resilient. For best results, leave on for 3–5 minutes before rinsing.",
      price: 170,
      comparePrice: 299,
      stock: 140,
      sku: "HC-HCG-100",
      images: [
        "https://treyfa.in/wp-content/uploads/2024/11/BOX-FRIST-PAGE-SAMPLEN-Recovered-1-406x406.png",
        "https://treyfa.in/wp-content/uploads/2024/11/01-9.jpg",
      ],
      tags: ["conditioner", "hibiscus", "hair-growth", "strength", "100ml"],
      isFeatured: false,
      rating: 5.0,
      reviewCount: 16,
      categoryId: hairCareCat.id,
    },
    {
      name: "Nourishing Hibiscus Shampoo for Hair Growth – Strength & Shine 100ML",
      slug: "hibiscus-shampoo-hair-growth-100ml",
      description: "A gentle yet effective hibiscus shampoo in a convenient 100ML size, perfect for individuals wanting to experience the transformative benefits of hibiscus hair care. This shampoo strengthens hair follicles, reduces hair fall, and promotes the growth of thicker, longer strands. Its conditioning agents leave hair naturally shiny and smooth without weighing it down.",
      price: 170,
      comparePrice: 299,
      stock: 160,
      sku: "HC-HHS-100",
      images: [
        "https://treyfa.in/wp-content/uploads/2024/11/BOX-FRIST-PAGE-SAMPLEN-Recovered-3-406x406.png",
        "https://treyfa.in/wp-content/uploads/2024/11/01-13.jpg",
      ],
      tags: ["shampoo", "hibiscus", "hair-growth", "shine", "100ml"],
      isFeatured: false,
      rating: 5.0,
      reviewCount: 11,
      categoryId: hairCareCat.id,
    },
    {
      name: "Powerful Choco Coffee Shampoo & Conditioner 200ML",
      slug: "choco-coffee-shampoo-conditioner-200ml",
      description: "An energizing 2-in-1 hair care treatment that combines the strengthening properties of coffee with the deep nourishment of chocolate. Caffeine penetrates the hair follicle to stimulate growth and counteract DHT-related hair thinning. Cocoa proteins fortify hair against breakage while natural butters from cocoa impart deep conditioning. Leaves hair stronger, more voluminous, and deliciously scented.",
      price: 200,
      comparePrice: 399,
      stock: 120,
      sku: "HC-CCS-200",
      images: [
        "https://treyfa.in/wp-content/uploads/2024/11/BOX-FRIST-PAGE-SAMPLE-12-406x406.png",
        "https://treyfa.in/wp-content/uploads/2024/11/01-6.jpg",
      ],
      tags: ["shampoo", "conditioner", "coffee", "chocolate", "2-in-1", "200ml"],
      isFeatured: true,
      rating: 4.91,
      reviewCount: 11,
      categoryId: hairCareCat.id,
    },
    {
      name: "Powerful Curry Leaves Hair Oil – Strengthen & Boost Hair Growth 100ML",
      slug: "curry-leaves-hair-oil-100ml",
      description: "Concentrated curry leaf extract in a light, non-greasy coconut oil base. Curry leaves are exceptionally rich in carbohydrates, fiber, calcium, phosphorous, iron, and vitamins, making this one of the most complete hair growth tonics available. It reverses premature greying, strengthens weak hair, stimulates new growth, and provides a deep scalp nourishment that shows visible results within weeks.",
      price: 175,
      comparePrice: 299,
      stock: 130,
      sku: "HC-CLO-100",
      images: [
        "https://treyfa.in/wp-content/uploads/2025/03/100-ML-7-406x406.jpg",
        "https://treyfa.in/wp-content/uploads/2025/03/01-9-406x406.jpg",
      ],
      tags: ["hair-oil", "curry-leaves", "hair-growth", "strengthen", "100ml"],
      isFeatured: false,
      rating: 5.0,
      reviewCount: 11,
      categoryId: hairCareCat.id,
    },
    {
      name: "Powerful Herbal Henna Black Hair Oil – Naturally Black & Strong Hair 100ML",
      slug: "herbal-henna-black-hair-oil-100ml",
      description: "A potent herbal hair oil that combines henna's natural color-binding and protein-fortifying properties with a nourishing coconut base. Henna's lawsone molecules naturally darken hair while keratin-binding agents strengthen each strand from within. This oil not only darkens but dramatically improves hair texture, reduces split ends, and creates a protective coating that prevents UV damage.",
      price: 175,
      comparePrice: 299,
      stock: 110,
      sku: "HC-HHB-100",
      images: [
        "https://treyfa.in/wp-content/uploads/2025/03/100-ML-6-406x406.jpg",
        "https://treyfa.in/wp-content/uploads/2025/03/03-9-406x406.jpg",
      ],
      tags: ["hair-oil", "henna", "black-hair", "herbal", "100ml"],
      isFeatured: false,
      rating: 4.91,
      reviewCount: 11,
      categoryId: hairCareCat.id,
    },
    {
      name: "Powerful Neem Anti Dandruff Shampoo & Conditioner 200ML",
      slug: "neem-anti-dandruff-shampoo-conditioner-200ml",
      description: "A comprehensive 2-in-1 anti-dandruff treatment in a generous 200ML size for the serious dandruff sufferer. Neem's active compounds — azadirachtin, nimbin, and nimbidin — work synergistically to eliminate dandruff-causing fungi, reduce scalp inflammation, and prevent recurrence. The conditioner component adds much-needed moisture to prevent the scalp dryness that perpetuates dandruff cycles.",
      price: 200,
      comparePrice: 399,
      stock: 100,
      sku: "HC-NAS-200",
      images: [
        "https://treyfa.in/wp-content/uploads/2024/11/BOX-FRIST-PAGE-SAMPLE-15-406x406.png",
        "https://treyfa.in/wp-content/uploads/2024/11/01-8.jpg",
      ],
      tags: ["shampoo", "conditioner", "neem", "anti-dandruff", "200ml"],
      isFeatured: false,
      rating: 4.82,
      reviewCount: 11,
      categoryId: hairCareCat.id,
    },
    {
      name: "Premium Basil Hair Oil & Body Care 200ML",
      slug: "basil-hair-oil-body-care-200ml",
      description: "A generous dual-purpose bottle of basil-infused oil that nourishes both hair and body. Holy basil (Tulsi) essential oil is rich in eugenol, linalool, and cineole — compounds with powerful antibacterial, antifungal, and anti-inflammatory properties. For hair, it combats scalp infections and stimulates growth. For body, it hydrates skin, reduces acne, and soothes inflammation. A truly versatile herbal preparation.",
      price: 200,
      comparePrice: 399,
      stock: 85,
      sku: "HC-BHO-200",
      images: [
        "https://treyfa.in/wp-content/uploads/2024/11/BOX-FRIST-PAGE-SAMPLE-26-406x406.png",
        "https://treyfa.in/wp-content/uploads/2024/11/01-25.jpg",
      ],
      tags: ["hair-oil", "basil", "body-care", "tulsi", "200ml"],
      isFeatured: false,
      rating: 4.88,
      reviewCount: 17,
      categoryId: hairCareCat.id,
    },
    {
      name: "Premium Coconut Henna Black Hair Oil 200ML",
      slug: "coconut-henna-black-hair-oil-200ml",
      description: "Our premium-sized henna and coconut oil formulation for those who want intensive, ongoing hair darkening and strengthening treatment. The concentrated henna-coconut blend provides progressive darkening with each application while coconut oil's protein-binding ability reinforces hair structure. After 8–12 weeks of regular use, hair is visibly darker, stronger, and has dramatically reduced breakage.",
      price: 200,
      comparePrice: 399,
      stock: 75,
      sku: "HC-CHB-200",
      images: [
        "https://treyfa.in/wp-content/uploads/2024/11/BOX-FRIST-PAGE-SAMPLE-28-406x406.png",
        "https://treyfa.in/wp-content/uploads/2024/11/01-31.jpg",
      ],
      tags: ["hair-oil", "henna", "coconut", "black-hair", "200ml"],
      isFeatured: false,
      rating: 5.0,
      reviewCount: 11,
      categoryId: hairCareCat.id,
    },
    {
      name: "Pure Virgin Coconut Oil with Vetiver 200ML",
      slug: "coconut-oil-with-vetiver-200ml",
      description: "A serene blend of pure virgin coconut oil and vetiver root, traditionally used in Tamil Nadu to combat summer heat and scalp irritation. Vetiver's cooling nature reduces scalp inflammation and itchiness, while coconut oil provides deep nourishment and protection against protein loss. The earthy, grounding aroma of vetiver also makes this a wonderful stress-relieving scalp massage oil.",
      price: 200,
      comparePrice: 399,
      stock: 90,
      sku: "HC-VCO-200",
      images: [
        "https://treyfa.in/wp-content/uploads/2024/11/BOX-FRIST-PAGE-SAMPLEN-Recovered-7-406x406.png",
        "https://treyfa.in/wp-content/uploads/2024/11/BOX-FRIST-PAGE-SAMPLEN-Recovered-9-406x406.png",
      ],
      tags: ["hair-oil", "coconut", "vetiver", "cooling", "200ml"],
      isFeatured: false,
      rating: 5.0,
      reviewCount: 10,
      categoryId: hairCareCat.id,
    },
    {
      name: "Restorative Coconut Hibiscus Hair Oil with Chamomile 30ML",
      slug: "coconut-hibiscus-hair-oil-30ml",
      description: "A travel-sized botanical fusion oil combining the restorative power of hibiscus and the soothing gentleness of chamomile in a coconut base. Chamomile adds a golden shimmer to lighter hair while reducing scalp sensitivity. Hibiscus repairs and strengthens each strand. This trio creates a perfectly balanced scalp-to-tip treatment in a convenient pocket-sized bottle.",
      price: 65,
      comparePrice: 72,
      stock: 220,
      sku: "HC-CHC-30",
      images: [
        "https://treyfa.in/wp-content/uploads/2025/04/30ml-4-406x406.jpg",
        "https://treyfa.in/wp-content/uploads/2025/04/01-7-406x406.jpg",
      ],
      tags: ["hair-oil", "hibiscus", "chamomile", "coconut", "30ml"],
      isFeatured: false,
      rating: 5.0,
      reviewCount: 8,
      categoryId: hairCareCat.id,
    },
    {
      name: "Restorative Hibiscus Chamomile Oil – Soothing Hair Growth 100ML",
      slug: "hibiscus-chamomile-hair-oil-100ml",
      description: "A calm, soothing hair growth oil for sensitive scalps. Chamomile's natural anti-inflammatory bisabolol and apigenin compounds reduce scalp redness and irritation, creating the optimal environment for healthy hair growth. Hibiscus provides growth stimulation and strengthening. This gentle yet effective formula is ideal for those with reactive scalps, postpartum hair loss, or stress-related thinning.",
      price: 175,
      comparePrice: 299,
      stock: 115,
      sku: "HC-HCO-100",
      images: [
        "https://treyfa.in/wp-content/uploads/2025/03/100ml-1-406x406.jpg",
        "https://treyfa.in/wp-content/uploads/2025/03/01-8-406x406.jpg",
      ],
      tags: ["hair-oil", "hibiscus", "chamomile", "soothing", "100ml"],
      isFeatured: false,
      rating: 5.0,
      reviewCount: 10,
      categoryId: hairCareCat.id,
    },
    {
      name: "Treyfa Choco Coffee Shampoo & Conditioner 30ML",
      slug: "coffee-shampoo-conditioner-30ml",
      description: "A trial-sized version of our energizing choco-coffee hair treatment. Perfect for first-time buyers or frequent travelers. Caffeine in this concentrated formula stimulates scalp microcirculation and awakens sluggish hair follicles, while cocoa proteins coat and strengthen each strand. Experience the luxury of café-inspired hair care anywhere, anytime.",
      price: 60,
      comparePrice: 72,
      stock: 300,
      sku: "HC-CCS-30",
      images: [
        "https://treyfa.in/wp-content/uploads/2025/04/30ml-1-406x406.jpg",
        "https://treyfa.in/wp-content/uploads/2025/04/01-5-406x406.jpg",
      ],
      tags: ["shampoo", "conditioner", "coffee", "chocolate", "30ml"],
      isFeatured: false,
      rating: 5.0,
      reviewCount: 8,
      categoryId: hairCareCat.id,
    },
    {
      name: "Treyfa Coconut Curry Hair Oil 30ML",
      slug: "coconut-curry-hair-oil-30ml",
      description: "A compact, travel-friendly version of our beloved Coconut Curry Leaves formula. Carrying generations of South Indian hair wisdom in every drop, this oil delivers curry leaves' exceptional nutrient payload — beta-carotene, proteins, and minerals — directly to hair follicles via a lightweight coconut oil carrier. Ideal for on-the-go scalp massages and pre-wash nourishment.",
      price: 65,
      comparePrice: 72,
      stock: 250,
      sku: "HC-CCL-30",
      images: [
        "https://treyfa.in/wp-content/uploads/2025/04/30ml-7-406x406.jpg",
      ],
      tags: ["hair-oil", "curry-leaves", "coconut", "30ml", "travel-size"],
      isFeatured: false,
      rating: 5.0,
      reviewCount: 8,
      categoryId: hairCareCat.id,
    },
    {
      name: "Treyfa Hibiscus Shampoo 30ML",
      slug: "treyfa-hibiscus-shampoo-30ml",
      description: "A travel-sized hibiscus shampoo that delivers the full potency of hibiscus flower extract in a gentle cleansing base. Ideal for those new to herbal hair care who want to experience the hibiscus difference before committing to a larger size. Sulfate-free formula preserves natural scalp oils while removing impurities.",
      price: 60,
      comparePrice: 72,
      stock: 280,
      sku: "HC-HHS-30",
      images: [
        "https://treyfa.in/wp-content/uploads/2025/04/30ML-6-406x406.jpg",
      ],
      tags: ["shampoo", "hibiscus", "30ml", "travel-size"],
      isFeatured: false,
      rating: 5.0,
      reviewCount: 8,
      categoryId: hairCareCat.id,
    },
    {
      name: "Treyfa Neem Anti-Dandruff Oil 100ML",
      slug: "treyfa-neem-anti-dandruff-oil-100ml",
      description: "A soothing scalp treatment oil that tackles dandruff and scalp irritation with the power of pure neem. This therapeutic oil should be applied directly to the scalp, massaged in, and left overnight for maximum efficacy. Neem's powerful antifungal action eliminates dandruff at the source while deeply moisturizing the scalp to prevent future flare-ups. Regular use restores scalp health naturally.",
      price: 175,
      comparePrice: 299,
      stock: 120,
      sku: "HC-NAO-100",
      images: [
        "https://treyfa.in/wp-content/uploads/2025/04/100-ml-406x406.jpg",
      ],
      tags: ["hair-oil", "neem", "anti-dandruff", "scalp-treatment", "100ml"],
      isFeatured: false,
      rating: 4.80,
      reviewCount: 9,
      categoryId: hairCareCat.id,
    },
    {
      name: "Treyfa Neem Anti-Dandruff Shampoo & Conditioner 30ML",
      slug: "neem-anti-dandruff-shampoo-conditioner-30ml",
      description: "A powerful travel-sized 2-in-1 anti-dandruff treatment that cleanses and conditions in one step. Formulated for clean, itch-free scalp maintenance on the go. Neem's active compounds provide lasting antifungal protection, making this ideal for business travelers who want to maintain their anti-dandruff routine without carrying multiple large bottles.",
      price: 60,
      comparePrice: 72,
      stock: 270,
      sku: "HC-NAS-30",
      images: [
        "https://treyfa.in/wp-content/uploads/2025/04/30-ML-406x406.jpg",
      ],
      tags: ["shampoo", "conditioner", "neem", "anti-dandruff", "30ml"],
      isFeatured: false,
      rating: 5.0,
      reviewCount: 8,
      categoryId: hairCareCat.id,
    },
    {
      name: "Turmeric Shampoo & Conditioner Set 200ML",
      slug: "turmeric-shampoo-conditioner-set-200ml",
      description: "A golden-hued 2-in-1 shampoo and conditioner set featuring Treyfa's signature turmeric formulation. Turmeric's anti-inflammatory and antifungal properties help maintain a healthy scalp environment, reducing dandruff and scalp sensitivity. Curcumin's antioxidant properties protect hair from environmental damage. The conditioning agents smooth the cuticle for radiant, manageable hair with each wash.",
      price: 200,
      comparePrice: 399,
      stock: 100,
      sku: "HC-TSC-200",
      images: [
        "https://treyfa.in/wp-content/uploads/2024/11/BOX-FRIST-PAGE-SAMPLE-10-406x406.png",
      ],
      tags: ["shampoo", "conditioner", "turmeric", "2-in-1", "200ml"],
      isFeatured: false,
      rating: 5.0,
      reviewCount: 9,
      categoryId: hairCareCat.id,
    },
    {
      name: "Turmeric Shampoo Conditioner 30ML",
      slug: "turmeric-shampoo-conditioner-30ml",
      description: "A travel-sized turmeric 2-in-1 hair treatment, perfect for sampling our golden herbal formula or for travel. Contains the same potent turmeric extract as our full-size product — conveniently packaged for everyday carry. Experience cleaner, healthier, more vibrant hair with the power of India's most celebrated spice.",
      price: 60,
      comparePrice: 72,
      stock: 290,
      sku: "HC-TSC-30",
      images: [
        "https://treyfa.in/wp-content/uploads/2025/04/30ml-10-406x406.jpg",
      ],
      tags: ["shampoo", "conditioner", "turmeric", "30ml", "travel-size"],
      isFeatured: false,
      rating: 5.0,
      reviewCount: 8,
      categoryId: hairCareCat.id,
    },
    {
      name: "Ultimate Choco Coffee Shampoo + Conditioner 100ML",
      slug: "choco-coffee-shampoo-conditioner-100ml",
      description: "A convenient 100ML size of our cult-favourite Choco Coffee 2-in-1 hair care treatment. This nourish-and-strengthen formula uses coffee's proven hair growth stimulation and cocoa's deep conditioning properties in a single, time-saving product. Ideal for busy individuals who want effective herbal hair care without the fuss of multiple products.",
      price: 170,
      comparePrice: 299,
      stock: 150,
      sku: "HC-CCS-100",
      images: [
        "https://treyfa.in/wp-content/uploads/2025/03/100-ML-2-406x406.jpg",
      ],
      tags: ["shampoo", "conditioner", "coffee", "chocolate", "100ml"],
      isFeatured: true,
      rating: 5.0,
      reviewCount: 9,
      categoryId: hairCareCat.id,
    },
    {
      name: "Ultimate Herbal Turmeric Shampoo + Conditioner 100ML",
      slug: "turmeric-shampoo-conditioner-100ml",
      description: "Our signature turmeric 2-in-1 formula in the ever-popular 100ML size. Golden turmeric has been used in South Indian hair rituals for centuries — now harnessed in a modern, effective shampoo-conditioner. Cleanses the scalp thoroughly, controls dandruff, reduces hair fall, and leaves hair gleaming with natural vitality. Suitable for all hair types.",
      price: 170,
      comparePrice: 299,
      stock: 180,
      sku: "HC-TSC-100B",
      images: [
        "https://treyfa.in/wp-content/uploads/2025/03/100-ML-4-406x406.jpg",
        "https://treyfa.in/wp-content/uploads/2025/03/01-5-406x406.jpg",
      ],
      tags: ["shampoo", "conditioner", "turmeric", "herbal", "100ml"],
      isFeatured: true,
      rating: 5.0,
      reviewCount: 9,
      categoryId: hairCareCat.id,
    },
  ];

  // ── Bath & Body Care Products (5) ─────────────────────────────────────
  const bathProducts = [
    {
      name: "Basil Heaven Basil Healing Body Oil 100ML",
      slug: "basil-healing-body-oil-100ml",
      description: "Sacred basil (Tulsi) body oil formulated for complete skin restoration. Applied after bathing, this lightweight oil absorbs rapidly to soothe inflamed skin, reduce acne on the body, and restore a healthy, luminous glow. Tulsi's powerful antimicrobial properties protect the skin barrier while its natural fragrance uplifts the senses. Ideal for dry skin, body acne, and post-sun skin recovery.",
      price: 175,
      comparePrice: 299,
      stock: 100,
      sku: "BB-BHO-100",
      images: [
        "https://treyfa.in/wp-content/uploads/2025/04/100-ml-1-406x406.jpg",
        "https://treyfa.in/wp-content/uploads/2025/04/01-406x406.jpg",
      ],
      tags: ["body-oil", "basil", "tulsi", "healing", "100ml"],
      isFeatured: false,
      rating: 4.73,
      reviewCount: 37,
      categoryId: bathBodyCat.id,
    },
    {
      name: "Pure Virgin Vetiver Coconut Body & Hair Oil 200ML",
      slug: "pure-vetiver-coconut-body-oil-200ml",
      description: "A holistic body and hair oil that blends the cooling, restorative properties of vetiver with the deep nourishment of virgin coconut oil. Vetiver has been used in India for centuries as a body coolant applied during hot summers — it reduces body heat, soothes skin inflammations, and promotes restful sleep through its calming aroma. As a body oil, it fades stretch marks, scars, and pigmentation.",
      price: 220,
      comparePrice: 399,
      stock: 80,
      sku: "BB-VCO-200",
      images: [
        "https://treyfa.in/wp-content/uploads/2024/11/BOX-FRIST-PAGE-SAMPLEN-Recovered-8-406x406.png",
        "https://treyfa.in/wp-content/uploads/2024/11/02-30.jpg",
      ],
      tags: ["body-oil", "vetiver", "coconut", "2-in-1", "200ml"],
      isFeatured: true,
      rating: 5.0,
      reviewCount: 11,
      categoryId: bathBodyCat.id,
    },
    {
      name: "Ultimate Choco Coffee Shower Shampoo + Conditioner 100ML",
      slug: "choco-coffee-bath-shampoo-100ml",
      description: "Transform your shower routine with this indulgent choco-coffee shampoo and conditioner. The energizing coffee scent awakens the senses while caffeine and cocoa compounds work synergistically to strengthen, nourish, and add body to your hair. A complete shower experience — cleanse, condition, and invigorate all in one bottle. Suitable for all hair types.",
      price: 170,
      comparePrice: 299,
      stock: 130,
      sku: "BB-CCS-100",
      images: [
        "https://treyfa.in/wp-content/uploads/2025/03/100-ML-2-406x406.jpg",
        "https://treyfa.in/wp-content/uploads/2025/03/01-3-406x406.jpg",
      ],
      tags: ["shampoo", "conditioner", "coffee", "chocolate", "bath", "100ml"],
      isFeatured: false,
      rating: 5.0,
      reviewCount: 9,
      categoryId: bathBodyCat.id,
    },
    {
      name: "Ultimate Herbal Turmeric Bath Shampoo + Conditioner 100ML",
      slug: "turmeric-bath-shampoo-conditioner-100ml",
      description: "A daily-use turmeric shampoo and conditioner for the bath. This all-in-one herbal hair care product cleanses with turmeric's natural antifungal properties, conditions with botanical emollients, and leaves hair smelling fresh and earthy. Ideal for those who prefer a streamlined bath routine without compromising on the quality of herbal ingredients.",
      price: 170,
      comparePrice: 299,
      stock: 140,
      sku: "BB-TSC-100",
      images: [
        "https://treyfa.in/wp-content/uploads/2025/03/100-ML-4-406x406.jpg",
        "https://treyfa.in/wp-content/uploads/2025/03/01-5-406x406.jpg",
      ],
      tags: ["shampoo", "conditioner", "turmeric", "bath", "100ml"],
      isFeatured: false,
      rating: 5.0,
      reviewCount: 9,
      categoryId: bathBodyCat.id,
    },
    {
      name: "2-in-1 Neem Dandruff Bath Shampoo + Conditioner 100ML",
      slug: "neem-dandruff-bath-shampoo-100ml",
      description: "A medically-inspired anti-dandruff shampoo-conditioner for those who want professional-level scalp care in a natural, herbal formulation. Designed for regular bath use, this 2-in-1 product makes anti-dandruff treatment effortless and consistent. Neem's active compounds provide lasting protection between washes while the conditioner maintains the moisture balance needed for a healthy scalp.",
      price: 170,
      comparePrice: 299,
      stock: 150,
      sku: "BB-NDS-100",
      images: [
        "https://treyfa.in/wp-content/uploads/2025/03/100-ML-3-406x406.jpg",
        "https://treyfa.in/wp-content/uploads/2025/03/01-4-406x406.jpg",
      ],
      tags: ["shampoo", "conditioner", "neem", "anti-dandruff", "bath", "100ml"],
      isFeatured: false,
      rating: 4.58,
      reviewCount: 45,
      categoryId: bathBodyCat.id,
    },
  ];

  // Insert all products
  const allProducts = [...faceProducts, ...hairProducts, ...bathProducts];
  let created = 0;
  for (const product of allProducts) {
    await prisma.product.upsert({
      where: { slug: product.slug },
      update: {},
      create: product,
    });
    created++;
  }

  console.log(`✅ ${created} products created`);
  console.log("\n🎉 Seed complete!");
  console.log("─────────────────────────────────");
  console.log("Admin:  admin@treyfa.in  / admin123");
  console.log("User:   user@treyfa.in   / user123");
  console.log("─────────────────────────────────");
  console.log(`Categories: 3`);
  console.log(`Products:   ${created} (8 face care · ${hairProducts.length} hair care · 5 bath & body)`);
}

main()
  .catch((e) => {
    console.error("❌ Seed failed:", e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
